version: "2"

services:
    jenkins:
        image: jenkins/jenkins
        restart: always
        environment:
            JENKINS_OPTS: --prefix=/jenkins
        ports:
            - "9000:8080"
    git:
        image: gogs/gogs
        restart: always
        volumes:
            - "./gogsdata:/data"
        ports:
            - "3000:3000"
    nginx:
        image: catwarrior/docker-nginx-amplify
        restart: always
        environment:
            API_KEY: 365ce49f97f955051ff1a13cbba4b647
            AMPLIFY_IMAGENAME: my-service-123
        volumes:
            - "./default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"
